/**
 * Convex API Auto-Generated File
 *
 * This file is typically generated by the Convex CLI when you run `npx convex dev`.
 * For the v0 preview environment, this stub provides the necessary type structure.
 *
 * In production, run `npx convex dev` to generate the full API definitions.
 */

// Type-safe API object structure for Convex functions
export const api = {
  users: {
    getUser: {} as any,
    updateTooltipPreferences: {} as any,
  },
  sessions: {
    createSession: {} as any,
    updateSession: {} as any,
    getSessions: {} as any,
    getSessionMessages: {} as any,
    addMessage: {} as any,
    getUserSessions: {} as any,
    getById: {} as any,
    updateTitle: {} as any,
  },
  messages: {
    create: {} as any,
    createMessage: {} as any,
    getMessages: {} as any,
    getBySession: {} as any,
    send: {} as any,
  },
  debates: {
    complete: {} as any,
  },
}

// Default export for compatibility
export default api
